apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oxide-controller
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.secretName }}"]
    verbs: ["get", "update", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oxide-controller
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: oxide-controller
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: oxide-controller
  apiGroup: rbac.authorization.k8s.io
