apiVersion: v1
kind: Service
metadata:
  name: oxide-controller
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: oxide-controller
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.image.port }}
